CREATE TRIGGER BOOK_RATING_AVERAGE_ON_INSERT AFTER INSERT ON REVIEW REFERENCING NEW AS INSERTED_ROW FOR EACH ROW MODE DB2SQL UPDATE BOOK SET BOOK.RATING=(SELECT AVG(RATING) AS AVERAGE FROM REVIEW WHERE INSERTED_ROW.BOOK=REVIEW.BOOK GROUP BY REVIEW.BOOK) WHERE INSERTED_ROW.BOOK=BOOK.ID;

CREATE TRIGGER BOOK_RATING_AVERAGE_ON_UPDATE  AFTER UPDATE ON REVIEW REFERENCING NEW AS UPDATED_ROW FOR EACH ROW MODE DB2SQL UPDATE BOOK SET BOOK.RATING=(SELECT AVG(RATING) AS AVERAGE FROM REVIEW WHERE UPDATED_ROW.BOOK=REVIEW.BOOK GROUP BY REVIEW.BOOK) WHERE UPDATED_ROW.BOOK=BOOK.ID;

CREATE TRIGGER BOOK_RATING_AVERAGE_ON_DELETE AFTER DELETE ON REVIEW REFERENCING OLD AS DELETED_ROW FOR EACH ROW MODE DB2SQL UPDATE BOOK SET BOOK.RATING=(SELECT AVG(RATING) AS AVERAGE FROM REVIEW WHERE DELETED_ROW.BOOK=REVIEW.BOOK GROUP BY REVIEW.BOOK) WHERE DELETED_ROW.BOOK=BOOK.ID;

CREATE TRIGGER BOOK_AMOUNT_SOLD AFTER INSERT ON PURCHASE_ORDER REFERENCING NEW AS INSERTED_ROW FOR EACH ROW MODE DB2SQL UPDATE BOOK SET BOOK.AMOUNT_SOLD=(SELECT SUM(AMOUNT) AS AMOUNT_SOLD_NEW FROM PURCHASE_ORDER WHERE INSERTED_ROW.BOOK=PURCHASE_ORDER.BOOK GROUP BY PURCHASE_ORDER.BOOK) WHERE INSERTED_ROW.BOOK=BOOK.ID;